name: Run Code Quality Checks

# Triggers the workflow on push or pull request events to the main branch
on:
  push:
    branches:
        - main
        - feature/*
  pull_request:
    branches:
        - main

# Defines the jobs that make up the workflow
jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make install

      - name: Run black check
        run: make black-check
    
      - name: Run mypy check
        run: make mypy

      - name: Run pylint check
        run: make pylint
